# Generated by Django 3.2.25 on 2025-04-05 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='CostoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateTimeField(verbose_name='Fecha y hora del evento')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio del evento')),
                ('hora_fin', models.TimeField(verbose_name='Hora de finalización del evento')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de confirmación')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de cancelación')),
                ('nombre_novio', models.CharField(max_length=200, verbose_name='Nombre novio')),
                ('nombre_novia', models.CharField(max_length=200, verbose_name='Nombre novia')),
                ('telefono_novio', models.CharField(max_length=50, verbose_name='Telefono novio')),
                ('telefono_novia', models.CharField(max_length=50, verbose_name='Telefono novia')),
                ('numero_personas', models.IntegerField(verbose_name='Numero de personas')),
                ('status', models.IntegerField(default=1)),
                ('contrato', models.BooleanField(default=False)),
                ('folio', models.CharField(max_length=100, verbose_name='Folio')),
                ('fecha_expiracion', models.DateTimeField(null=True, verbose_name='Fecha de expiracion')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='(Numero de personas * platillo)')),
                ('npb', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='(Numero de personas * bebidas)')),
                ('npm', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='(Numero de personas * meseros)')),
                ('npj', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='(Numero de personas * uso jardin)')),
                ('npc', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='(Numero de personas * Complemento)')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='(Costo fijo + npp + npb + npm + npj + npc)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='Platillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('telefono', models.CharField(max_length=150, verbose_name='Correo')),
                ('password', models.CharField(max_length=250)),
                ('tipo', models.IntegerField(default=1, verbose_name='Administrador / Coordinador')),
                ('identificacion', models.CharField(max_length=50, verbose_name='Identificacion')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_cotizacion', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta de la cotizacion')),
                ('url_contrato', models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta del contrato')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_cotizacion', to='casadimaria.cotizacion')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='creada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creada_usuario', to='casadimaria.usuario'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_cotizacion', to='casadimaria.evento'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='platillo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platillo_cotizacion', to='casadimaria.platillo'),
        ),
    ]
