# Generated by Django 3.2.25 on 2025-04-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casadimaria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización')),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.IntegerField(default=1, verbose_name='Administrador = 1 / Coordinador'),
        ),
    ]
