# Generated by Django 3.2.25 on 2025-04-08 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casadimaria', '0002_auto_20250407_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='adicional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complemento_cotizacion', to='casadimaria.complemento'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='correo_electronico',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Correo novio'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='nombre_novia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre novia'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='telefono_novia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefono novia'),
        ),
    ]
