# Generated by Django 3.2.25 on 2025-04-08 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casadimaria', '0003_auto_20250408_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecotizacion',
            name='cotizacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_cotizacion', to='casadimaria.cotizacion'),
        ),
    ]
