# Generated by Django 3.2.25 on 2025-04-08 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casadimaria', '0004_detallecotizacion_cotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='colaborador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='colaborar_cotizacion', to='casadimaria.colaboradore'),
        ),
    ]
