# Generated by Django 3.2.25 on 2025-04-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casadimaria', '0005_cotizacion_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaboradore',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
