# Generated by Django 3.2.25 on 2025-04-24 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casadimaria', '0006_auto_20250408_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatilloJovene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Última actualización')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='numero_jovenes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de personas jovenes'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='platillo_jovenes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platillo_jovenes_cotizacion', to='casadimaria.platillojovene'),
        ),
    ]
